### ISSUE TITLE
Add LICENSE, maybe add GPLv3 GCC exception

### ISSUE THREAD

**Issue by phoe** [equwal/minimalist-template#1]
* GPLv3 requires the license text to be distributed along with the software. You could add the license text to the repository.
* GPLv3 is viral by default, so all projects which utilized this template will need to be distributed under GPLv3. Unless that is the intended behaviour, please add a [license exception](https://www.gnu.org/licenses/gcc-exception-3.1.en.html) that allows the resulting work to be licensed under any license.

**Comment by equwal** [comment]
> * GPLv3 is viral by default, so all projects which utilized this template will need to be
> distributed under GPLv3. Unless that is the intended behaviour, please add a [license exception](https://www.gnu.org/licenses/gcc-exception-3.1.en.html) 
that allows the resulting work to be licensed under any license.

Since it is important to you, I'll switch to MIT.
